// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClsFWpYhs-DOWJ36Y8xY320XS2ItK3kMo',
    appId: '1:499066921315:web:05f8e769a682e6fed2b356',
    messagingSenderId: '499066921315',
    projectId: 'vs6451071010',
    authDomain: 'vs6451071010.firebaseapp.com',
    storageBucket: 'vs6451071010.firebasestorage.app',
    measurementId: 'G-TK5YBJS28F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5m4vo8Rf71JY9IAlygWj1Hq0hBKrlddE',
    appId: '1:499066921315:android:23dbd89722080aead2b356',
    messagingSenderId: '499066921315',
    projectId: 'vs6451071010',
    storageBucket: 'vs6451071010.firebasestorage.app',
  );
}
